
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import HashEscrowContractArtifactJson from '../../contracts/hash_escrow/target/hash_escrow-HashEscrow.json' with { type: 'json' };
export const HashEscrowContractArtifact = loadContractArtifact(HashEscrowContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract HashEscrow;
 */
export class HashEscrowContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, HashEscrowContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): HashEscrowContract {
    return Contract.at(address, HashEscrowContract.artifact, wallet) as HashEscrowContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, ) {
    return new DeployMethod<HashEscrowContract>(PublicKeys.default(), wallet, HashEscrowContractArtifact, (instance, wallet) => HashEscrowContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, ) {
    return new DeployMethod<HashEscrowContract>(publicKeys, wallet, HashEscrowContractArtifact, (instance, wallet) => HashEscrowContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof HashEscrowContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<HashEscrowContract['methods'][M]>
  ) {
    return new DeployMethod<HashEscrowContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      HashEscrowContractArtifact,
      (instance, wallet) => HashEscrowContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return HashEscrowContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(HashEscrowContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'secret_hash' | 'token_addr' | 'amount' | 'claimed'> {
      return {
        secret_hash: {
      slot: new Fr(1n),
    },
token_addr: {
      slot: new Fr(3n),
    },
amount: {
      slot: new Fr(5n),
    },
claimed: {
      slot: new Fr(7n),
    }
      } as ContractStorageLayout<'secret_hash' | 'token_addr' | 'amount' | 'claimed'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** deposit(token: struct, amount: integer, secret_hash: field, nonce: field) */
    deposit: ((token: AztecAddressLike, amount: (bigint | number), secret_hash: FieldLike, nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_amount() */
    get_amount: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_secret_hash() */
    get_secret_hash: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_token() */
    get_token: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_claimed() */
    is_claimed: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((message_ciphertext: FieldLike[], message_context: { tx_hash: FieldLike, unique_note_hashes_in_tx: FieldLike[], first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_private_state() */
    sync_private_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** withdraw(secret: field, recipient: struct, token: struct, amount: integer) */
    withdraw: ((secret: FieldLike, recipient: AztecAddressLike, token: AztecAddressLike, amount: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
